edition = "2021"

use_field_init_shorthand = true
use_try_shorthand = true

# hex_literal_case = "Upper"
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

# condense_wildcard_suffixes = true
# format_macro_matchers = true
# format_strings = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# reorder_impl_items = true
# skip_children = true

# format_code_in_doc_comments = true
# normalize_comments = true
# wrap_comments = true
