hex_literal_case = "Upper"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

condense_wildcard_suffixes = true
disable_all_formatting = true
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
hide_parse_errors = true
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
skip_children = true
space_before_colon = true
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true