[[provider]]
name = "search"
command = "python"
args = ["~/.config/ellie/functions/metaphor.py", "search"]

[[provider]]
name = "find_similar"
command = "python"
args = ["~/.config/ellie/functions/metaphor.py", "find_similar"]

[[provider]]
name = "wolframalpha"
command = "python"
args = ["~/.config/ellie/functions/wolframalpha.py"]
