[build]
rustc-wrapper = "sccache"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=/usr/bin/mold"]
