theme = "monokai_pro"

[editor]
line-number = "relative"
color-modes = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"

[editor.statusline]
right = [
  "selections",
  "file-type",
  "diagnostics",
  "file-encoding",
  "file-line-ending",
  "position-percentage",
  "position",
]

[editor.whitespace.render]
tab = "all"
