[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

# Prettier (tested ones, see <https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#prettier>)

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

# Prettier (untested ones, see above)

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--parser", "scss"] }
auto-format = true

[[language]]
name = "graphql"
formatter = { command = "prettier", args = ["--parser", "graphql"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

# Prettier (untested ones, official plugins, see above)

[[language]]
name = "php"
formatter = { command = "prettier", args = ["--parser", "php"] }
auto-format = true

[[language]]
name = "ruby"
formatter = { command = "prettier", args = ["--parser", "ruby"] }
auto-format = true

[[language]]
name = "xml"
formatter = { command = "prettier", args = ["--parser", "xml"] }
auto-format = true

# Deno (tested ones, see <https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#deno>)

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true
